// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHc_ZIavjWxCunl1xj0ajV_OeRMPBDTkA',
    appId: '1:583593536789:web:62e2e513c80e9a7e804d1c',
    messagingSenderId: '583593536789',
    projectId: 'practia-push',
    authDomain: 'practia-push.firebaseapp.com',
    storageBucket: 'practia-push.firebasestorage.app',
    measurementId: 'G-LK3KKX1TYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM-AyDtsQhO3QlmfpIFe3Sy5M3l_zUhTE',
    appId: '1:583593536789:android:ced0016fa3b19844804d1c',
    messagingSenderId: '583593536789',
    projectId: 'practia-push',
    storageBucket: 'practia-push.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYPm9IBJscfpB3eECSS1dphZq0Yz1ZQa0',
    appId: '1:583593536789:ios:d84b83eabcf17cc6804d1c',
    messagingSenderId: '583593536789',
    projectId: 'practia-push',
    storageBucket: 'practia-push.firebasestorage.app',
    iosBundleId: 'com.example.pushNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYPm9IBJscfpB3eECSS1dphZq0Yz1ZQa0',
    appId: '1:583593536789:ios:d84b83eabcf17cc6804d1c',
    messagingSenderId: '583593536789',
    projectId: 'practia-push',
    storageBucket: 'practia-push.firebasestorage.app',
    iosBundleId: 'com.example.pushNotifications',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHc_ZIavjWxCunl1xj0ajV_OeRMPBDTkA',
    appId: '1:583593536789:web:88e76f4b96aaa050804d1c',
    messagingSenderId: '583593536789',
    projectId: 'practia-push',
    authDomain: 'practia-push.firebaseapp.com',
    storageBucket: 'practia-push.firebasestorage.app',
    measurementId: 'G-ZPW5F4G9V5',
  );
}
